version: "3.3"
services:
    nodeserver:
       image: ghcr.io/joaomouraosa/mock_nodeserver
       restart: always
       build:
           context: ./server
       ports:
           - "5000:5000"
    nginx:
        image: ghcr.io/joaomouraosa/mock_nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"